# 股票初筛因子配置文件
# 此文件包含所有因子的参数配置，可根据市场情况调整

# 启用的因子列表
# 可以通过注释或删除来禁用特定因子
factors:
  - pe_ratio      # 市盈率因子
  - volatility    # 波动率因子
  - volume        # 成交量因子
  - trend         # 趋势因子
  - price_range   # 价格区间因子
  - market_cap    # 市值因子
  - turnover      # 换手率因子

# 市盈率因子配置
pe_ratio:
  max_pe: 50.0    # 最大市盈率阈值
                  # 建议值: 科创板可放宽至100，主板保持在50以内
                  # 成长股可适当放宽，价值股可适当收紧

# 波动率因子配置
volatility:
  min_volatility: 0.05  # 最小波动率阈值（5%）
  max_volatility: 0.50  # 最大波动率阈值（50%）
  lookback_days: 180    # 回看天数
                        # 建议值: 震荡市可收窄至0.05-0.30
                        # 牛熊市可放宽至0.05-0.50

# 成交量因子配置
volume:
  min_volume: 5000      # 最小日均成交量（手）
                        # 建议值: 主板>=5000手，科创板>=2000手
  lookback_days: 180    # 回看天数

# 趋势因子配置
trend:
  min_trend: -0.3       # 最小年化趋势阈值（-30%）
  max_trend: 0.3        # 最大年化趋势阈值（30%）
  lookback_days: 180    # 回看天数
                        # 建议值: 震荡市可收窄至±20%
                        # 趋势市可放宽至±40%

# 价格区间因子配置
price_range:
  min_price: 5.0        # 最小价格阈值（元）
  max_price: 100.0      # 最大价格阈值（元）
                        # 建议值: 根据资金量调整
                        # 小资金建议5-50元
                        # 大资金可放宽至5-200元

# 市值因子配置
market_cap:
  min_market_cap: 50.0   # 最小市值阈值（亿元）
  max_market_cap: 1000.0 # 最大市值阈值（亿元）
                         # 建议值: 
                         # 小市值: 50-300亿
                         # 中市值: 300-1000亿
                         # 大市值: >1000亿

# 换手率因子配置
turnover:
  min_turnover: 0.01     # 最小换手率阈值（1%）
  max_turnover: 0.05     # 最大换手率阈值（5%）
  lookback_days: 180     # 回看天数
                         # 建议值: 
                         # 活跃股可放宽至1%-10%
                         # 稳定股可收窄至1%-3%

# 注意事项：
# 1. 所有阈值都可以根据市场情况动态调整
# 2. 回看天数可以根据策略周期调整，一般建议180天左右
# 3. 不同板块（主板、科创板等）可以使用不同的阈值
# 4. 建议定期（如每季度）根据市场情况审视并调整参数