[project]
authors = [
  {name = "丁鲁攀", email = "1164764881@qq.com"},
]
dependencies = []
description = "Add your description here"
name = "trading-grid"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"

[project.scripts]
cli = "trading_grid.cli:app"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
