# 最小网格策略配置
symbol: BTC/USDT
base_currency: BTC
quote_currency: USDT

# 价格区间
lower_bound: 50000
upper_bound: 70000
grid_count: 20            # 区间数量；层级数 = grid_count + 1
grid_spacing_mode: FIXED_% # 或 ATR_K, BBANDS_K
grid_spacing_pct: 1.5     # 当使用 FIXED_% 时使用

# 资金
allocate_quote: 10000
capital_reserve_pct: 0.3   # 保留30%现金用于应急

# 费用和风险
fee_rate: 0.001            # 0.1% 挂单/吃单平均费用（演示用）
take_profit_breakout: true
stop_loss_pct_below: 0.08  # 如果价格 < lower_bound*(1-0.08) 则止损
trailing_exit_pct: 0.0     # 设置 >0 以启用追踪止盈
max_open_orders: 200
rebalance_on_fill: true

# 回测数据
data_csv: sample_ohlcv.csv # 提供您自己的OHLCV数据：timestamp,open,high,low,close,volume
timeframe: 1m