[project]
authors = [
  {name = "丁鲁攀", email = "1164764881@qq.com"},
]
dependencies = []
description = "Add your description here"
name = "core"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"

[project.scripts]
cli = "core.cli:app"
core = "core:main"
sync-all = "core.cli:sync_all"
sync-hist = "core.cli:main"
version = "core.cli:version"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
