name: 同步全量股票数据

on:
  schedule:
    - cron: '0/30 0-17 * * *'  # 每天的 30分钟触发一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run_weekday_task:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 拉取代码

    - name: Set up Python
      uses: actions/setup-python@v4  # 设置 Python 环境
      with:
        python-version: '3.9'  # 设置所需的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync  # 同步 uv 环境
        uv build  # 构建 uv 环境

    - name: Run Python script
      env: # 将 secrets 作为环境变量传递
          TG_TOKEN: ${{ secrets.TG_TOKEN }}  
      run: |
        pwd
        ls -la
        echo Starting script...
        CUR_DATE=$(date +"%Y%m%d")
        echo "Current date: $CUR_DATE"
        uv run --package core cli sync-all
        uv run --package core cli sync-hist-all --end-date $CUR_DATE --adjust hfq --max-workers 5
    - name: Commit and push generated files
      run: |
        pwd
        ls -la
        git config --global user.name "DLuPan"
        git config --global user.email "wingsgod@outlook.com"
        git status
        git add .
        git status
        git commit -m "Add daily generated file for weekdays"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
