[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "丁鲁攀", email = "1164764881@qq.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
tools = "tools:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
